### ISSUE TITLE
Blender 2.79b / Debian 9

### ISSUE THREAD

**Issue by ehmar** [i-Reboot/CutAwayShader#2]
I just found your add-on. It's exactly what I need and looks amazing, but I can't get it working. : (

I'm using 2.79b.
Enabled the addon and auto execution of Python.
(followed your installation video)

When I try to add the cutaway shader node, there are no connections and no inputs/outputs to connect my material.
![untitled](https://user-images.githubusercontent.com/31894689/45588571-d62b0d00-b8e4-11e8-9785-afb16089efdb.jpg)

Does this addon work in 2.79? 
Do I have to enable something else in blender (OSL)?
Or am I missing something ridiculously simple?

Are you still maintaining this addon? 
If not, do you know of a similar feature for rendering cutaways on complex models?

Thanks

**Comment by ehmar** [comment]
Forgot to check the console. I'm getting this when I try to add the node...
```
Traceback (most recent call last):
  File "/home/user/.config/blender/2.79/scripts/addons/node_cutaway_shader/__init__.py", line 1278, in init
    osl_node.inputs["DrawMode_circular0_rectangular1"].default_value = self.rectangular_circular_int    # set the OSL shader's draw mode (circular 0, rect 1 , cutaway image 2)
KeyError: 'bpy_prop_collection[key]: key "DrawMode_circular0_rectangular1" not found'

location: /usr/share/blender/scripts/startup/bl_operators/node.py:92
```

**Comment by ehmar** [comment]
I ended up "downgrading" my model to Blender 2.78 so I could use this addon. It really is a great feature, and I hope you, or someone smarter than me can pick up this project, improve it, and get it included in future Blender releases.

**Comment by i-Reboot** [comment]
Hi Ehmar, thanks for the feedback. Sorry for the slow reply! I just tried the add on on 2.79b and it worked on my machine (I tried linux but not Win 10 yet)

From your screen shot it looks as though the OSL script hasn't loaded - but the python script has (you can check this by looking in Blenders . text editors. There should be two 'text blocks' loaded). Maybe try un-installing and then re-installing?

I plan to upgrade the add on when the API for Blender 2.8 comes out.

Cheers Dylan

**Comment by ehmar** [comment]
Thanks for the response. I was worried you abandoned the project. It's a great feature. Hope it's not too much work to keep it current (for 2.8).

I do see the scripts in the text node, but if I click the "Script Node Update" button, it gives an error that OSL is disabled for this build.
![untitled](https://user-images.githubusercontent.com/31894689/46476883-424bb300-c7b7-11e8-87a5-20fc41376bcd.jpg)

I'm using a Debian 9 Blender package. So maybe they didn't build it properly(?). Will try with an official 2.79 download from Blender.org.

Thanks again. And keep up the great work!

**Comment by ehmar** [comment]
Confirmed that the problem is with Debian 9's build of blender. They apparently don't have OSL enabled. Downloading the official [blender.org build](https://www.blender.org/download/releases/2-79/) works fine.

Closing this issue.

Here's how I used the cutaway add-on...
![untitled](https://user-images.githubusercontent.com/31894689/46543782-be192e80-c88f-11e8-9def-c817d4163d82.jpg)
